# Generated by Django 5.2.1 on 2025-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
