# Generated by Django 5.2.1 on 2025-08-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_resort_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
